name: 'MOS_L'
expected_strides:
  - 8
layers:
  - name: 'MosAttention'
    kernel_size: 1
    hidden_size: 32
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 32
  - name: 'SparseMaxPool'
    kernel_size: 2
  - name: 'TemporalDropout'
    window_size: 4
  # stride 2 feature size 64
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 64
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 64
  - name: 'SparseMaxPool'
    kernel_size: 2
  - name: 'TemporalDropout'
    window_size: 4
  # stride 4 feature size 128
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 128
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 128
  - name: 'SparseMaxPool'
    kernel_size: 2
  - name: 'TemporalDropout'
    window_size: 4
  # stride 8 feature size 256
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 256
  - name: 'MosAttention'
    kernel_size: 3
    hidden_size: 256